name: example
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  fform:
    path: ../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
